name: Test and Dockerize Job-Prep application
on: 
  push:
    branches:
      - main
jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Build docker image and run
        run: |
          docker build -t job-prep .
          docker run --name job-prep -d --env-file .env -p 8501:8501 job-prep

      - name: Run tests inside docker container
        run: docker exec job-prep pytest

  build-container:
    name: Build Docker container image
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: lawlietrzk/job_prep
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          push: true
          tags: latest, ${{ github.run_number }}