name: Test and Dockerize Job-Prep application
on: 
  push:
    branches:
      - main
jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Build docker image and run
        run: |
          docker build -t job-prep .
          docker run --name job-prep -d --env-file .env -p 8501:8501 job-prep

      - name: Run tests inside docker container
        run: docker exec job-prep pytest

  build-container:
    name: Build Docker container image
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lawlietrzk/job_prep
          tags: latest, ${{ github.run_number }}